const NS = "@hn/posts";

export const FETCH_POST_IDS_REQUEST = `${NS}/FETCH_POST_IDS_REQUEST`;
export const FETCH_POST_IDS_SUCCESS = `${NS}/FETCH_POST_IDS_SUCCESS`;
export const FETCH_POST_IDS_FAILURE = `${NS}/FETCH_POST_IDS_FAILURE`;
export const FETCH_POSTS_REQUEST = `${NS}/FETCH_POSTS_REQUEST`;
export const FETCH_POSTS_SUCCESS = `${NS}/FETCH_POSTS_SUCCESS`;
export const FETCH_POSTS_FAILURE = `${NS}/FETCH_POSTS_FAILURE`;
